ESX = exports['es_extended']:getSharedObject()


PlayerInEntry = false
LegalnpcSpawned = false
IllegalnpcSpawned = false
IsLoopClosed = false
LegalPressed = false
IllegalPressed = false
EnabledNUI = false
legal = false
PlayerNearLegalNPC = false
PlayerNearIllegalNPC = false

-- illegal cutscene
RegisterNetEvent('GMD_Entry:IllegalCutscene')
AddEventHandler('GMD_Entry:IllegalCutscene', function(source)
    if Config.UseIllegalCutscene then
    local playerPed = PlayerPedId()
    DoScreenFadeOut(1000)
    Wait(1000)
    SetEntityCoords(playerPed, 5256.495, -4802.694, -0.408, false, false, false, false)
    PlayerInEntry = true
    SetPlayerInvincible(playerPed, true)
    SetTimecycleModifier("intensity")
    ESX.Game.SpawnVehicle('patrolboat', vector3(5256.495, -4802.694, -0.408), 55.122, function(boat)
        SetEntityAsMissionEntity(boat, true, true)
        SetPedIntoVehicle(playerPed, boat, -2)
        local cam = CreateCam("DEFAULT_SCRIPTED_CAMERA", true)
        SetCamActive(cam, true)
        RenderScriptCams(true, false, 0, true, false)
        local npcModel = Config.IllegalPed
        RequestModel(npcModel)
        while not HasModelLoaded(npcModel) do
            Citizen.Wait(10)
        end
        local ModelHash = Config.IllegalVehicle
        if not IsModelInCdimage(ModelHash) then return end
        RequestModel(ModelHash)
        while not HasModelLoaded(ModelHash) do
          Wait(0)
        end
        SetCamCoord(cam, GetEntityCoords(boat))
        SetCamFov(cam, 50.0)
        AttachCamToEntity(cam, boat, 0.0, 10.0, 2.0, true)
        PointCamAtEntity(cam, boat, 0.0, 0.0, 0.0, true)
        local npcPed = CreatePed(4, npcModel, 5256.495, -4802.694, -0.408, 55.122, true, false)
        local npcPed2 = CreatePed(4, npcModel, 5256.495, -4802.694, -0.408, 55.122, true, false)
        local npcPed3 = CreatePed(4, npcModel, 5256.495, -4802.694, -0.408, 55.122, true, false)
        local npcPed4 = CreatePed(4, npcModel, 5064.160, -4641.867, 2.500, 235.663, true, false)
        local npcPed5 = CreatePed(4, npcModel, 5061.875, -4634.044, 2.525, 335.753, true, false)
        local npcPed6 = CreatePed(4, npcModel, 5062.501, -4632.385, 2.518, 152.253, true, false)
        local npcPed7 = CreatePed(4, npcModel, 5061.875, -4634.044, 2.525, 335.753, true, false)
        SetPedIntoVehicle(npcPed, boat, -1)
        SetPedIntoVehicle(npcPed2, boat, 1)
        SetPedIntoVehicle(npcPed3, boat, 2)
        SetEntityAsMissionEntity(npcPed, true, true)
        SetModelAsNoLongerNeeded(npcModel)
        local textDisplayed = false
        local playerCoords = GetEntityCoords(playerPed)
        local targetCoords = vector4(5094.419, -4650.524, -0.334, 67.759)
        SetDriverAbility(npcPed, 1.0)
        SetDriverAggressiveness(npcPed, 0.0)
        SetDriverAggressiveness(npcPed2, 0.0)
        SetDriverAggressiveness(npcPed3, 0.0)
        TaskVehicleDriveWander(npcPed, boat, 15.0, 56)
        TaskVehicleDriveToCoordLongrange(npcPed, boat, targetCoords.x, targetCoords.y, targetCoords.z, 10.0, 1, GetEntityModel(boat), 1074528293, 1.0, true)
        Config.IllegalCutSceneText1()
        RenderScriptCams(false, false, 0, true, false)
        SetEntityCoords(boat, 5094.419, -4650.524, -0.334)
        SetEntityHeading(boat, 67.759)
        FreezeEntityPosition(boat, true)
        SetEntityCoords(playerPed, 5084.094, -4652.558, 2.027)
        SetEntityHeading(playerPed, 74.801)
        SetEntityCoords(npcPed, 5081.259, -4651.701, 2.225)
        SetEntityHeading(npcPed, 251.899)
        SetPedRelationshipGroupHash(npcPed, GetHashKey("MILITARY"))
        SetPedAccuracy(npcPed, 70)
        SetPedDropsWeaponsWhenDead(npcPed, false)
        local taskID = TaskStartScenarioInPlace(npcPed, "WORLD_HUMAN_AA_SMOKE", 0, true)
        SetEntityCoords(npcPed2, 5080.265, -4654.217, 2.259)
        SetEntityHeading(npcPed2, 305.409)
        GiveWeaponToPed(npcPed2, GetHashKey("WEAPON_CARBINERIFLE"), 250, true, true)
        SetEntityCoords(npcPed3, 5081.381, -4649.488, 2.269)
        SetEntityHeading(npcPed3, 217.511)
        SetPedRelationshipGroupHash(npcPed3, GetHashKey("MILITARY"))
        GiveWeaponToPed(npcPed3, GetHashKey("WEAPON_CARBINERIFLE"), 250, true, true)
        SetEntityCoords(npcPed4, 5064.160, -4641.867, 2.500)
        SetEntityHeading(npcPed4, 235.663)
        SetPedRelationshipGroupHash(npcPed4, GetHashKey("MILITARY"))
        GiveWeaponToPed(npcPed4, GetHashKey("WEAPON_CARBINERIFLE"), 250, true, true)
        SetEntityCoords(npcPed7, 5061.875, -4634.044, 2.525)
        SetEntityHeading(npcPed7, 335.753)
        SetPedRelationshipGroupHash(npcPed7, GetHashKey("MILITARY"))
        TaskStartScenarioInPlace(npcPed7, "WORLD_HUMAN_AA_SMOKE", 0, true)
        SetEntityCoords(npcPed6, 5062.501, -4632.385, 2.518)
        SetEntityHeading(npcPed6, 152.253)
        SetPedRelationshipGroupHash(npcPed6, GetHashKey("MILITARY"))
        GiveWeaponToPed(npcPed6, GetHashKey("WEAPON_CARBINERIFLE"), 250, true, true)
        local FrontCar = CreateVehicle(ModelHash, 5058.710, -4633.417, 2.667, 37.034, true, false)
        SetVehicleEngineOn(FrontCar, true, true, false)
        local MiddleCar = CreateVehicle(ModelHash, 5062.612, -4643.323, 2.604, 18.241, true, false)
        SetVehicleEngineOn(MiddleCar, true, true, false)
        SetPedIntoVehicle(npcPed4, MiddleCar, -1)
        SetPedIntoVehicle(npcPed5, MiddleCar, 1)
        SetModelAsNoLongerNeeded(ModelHash)
        local playerCoords = GetEntityCoords(playerPed)
        SetCamCoord(cam, playerCoords.x, playerCoords.y, playerCoords.z + 1.5)
        PointCamAtEntity(cam, npcPed, 0.0, 0.0, 0.0, true)
        RenderScriptCams(true, false, 0, true, true)
        SetCamActiveWithInterp(cam, camPrev, 500, true, true)
        SetCamFov(cam, 20.0)
        Citizen.CreateThread(function()
            while true do
                Citizen.Wait(0)
                SetCamCoord(cam, GetEntityCoords(playerPed))
                PointCamAtEntity(cam, npcPed, 0.0, 0.0, 0.0, true)
            end
        end)
        Config.IllegalCutSceneText2()
        ClearPedTasks(npcPed, taskID)
        TaskGoStraightToCoord(playerPed, 5063.989, -4646.964, 2.649, 1.0, -1, 1.0, 0.0)
        TaskGoStraightToCoord(npcPed, 5064.986, -4641.952, 2.516, 0.2, -1, 1.0, 0.0)
        Wait(1000)
        TaskGoStraightToCoord(npcPed2, 5066.629, -4641.946, 2.433, 0.2, -1, 1.0, 0.0)
        TaskGoStraightToCoord(npcPed3, 5066.629, -4641.946, 2.433, 0.2, -1, 1.0, 0.0)
        Config.IllegalCutSceneText3()
        TaskEnterVehicle(npcPed6, FrontCar, -1, -1, 1.0, 1, 0)
        TaskEnterVehicle(npcPed7, FrontCar, -1, 0, 1.0, 1, 0)
        TaskEnterVehicle(npcPed2, FrontCar, -1, 1, 1.0, 1, 0)
        TaskEnterVehicle(npcPed3, FrontCar, -1, 2, 1.0, 1, 0)
        TaskEnterVehicle(npcPed, MiddleCar, -1, 0, 1.0, 1, 0)
        Wait(2500)
        TaskEnterVehicle(playerPed, MiddleCar, -1, 2, 1.0, 1, 0)
        SetCamActive(cam, true)
        RenderScriptCams(true, false, 0, true, false)
        SetCamCoord(cam, GetEntityCoords(MiddleCar))
        SetCamFov(cam, 50.0)
        AttachCamToEntity(cam, MiddleCar, 0.0, -10.0, 5.0, true)
        PointCamAtEntity(cam, MiddleCar, 0.0, 0.0, 0.0, true)
        Wait(10000)
        TaskVehicleDriveToCoordLongrange(npcPed6, FrontCar, 5230.683, -5212.716, 16.354, 10.0, 1, GetEntityModel(FrontCar), 1074528293, 1.0, true)
        Wait(500)
        TaskVehicleDriveToCoordLongrange(npcPed4, MiddleCar, 5230.683, -5212.716, 16.354, 10.0, 1, GetEntityModel(MiddleCar), 1074528293, 1.0, true)
        Config.IllegalCutSceneText4()
        SetEntityCoords(FrontCar, 5217.035, -5110.573, 4.626)
        SetEntityHeading(FrontCar,  226.491)
        FreezeEntityPosition(FrontCar, true)
        SetVehicleEngineOn(FrontCar, false, true, false)
        SetEntityCoords(MiddleCar, 5205.643, -5106.092, 4.022)
        SetEntityHeading(MiddleCar,  260.937)
        FreezeEntityPosition(MiddleCar, true)
        SetVehicleEngineOn(MiddleCar, false, true, false)
        Wait(2000)
        Config.IllegalCutSceneText5()
        TaskLeaveVehicle(playerPed, MiddleCar, 0)
        TaskLeaveVehicle(npcPed, MiddleCar, 0)
        Wait(2500)
        TaskGoStraightToCoord(playerPed, 5209.929, -5122.375, 6.125, 1.0, -1, 1.0, 0.0)
        TaskGoStraightToCoord(npcPed, 5209.929, -5122.375, 6.125, 0.2, -1, 1.0, 0.0)
        Wait(3000)
        FreezeEntityPosition(FrontCar, false)
        FreezeEntityPosition(MiddleCar, false)
        Config.IllegalCutSceneText6()
        Wait(2000)
        ClearPedTasks(playerPed)
        SetEntityAsMissionEntity(boat, false, false)
        DeleteVehicle(boat)
        DeleteVehicle(FrontCar)
        DeleteVehicle(MiddleCar)
        DeletePed(npcPed)
        DeletePed(npcPed2)
        DeletePed(npcPed3)
        DeletePed(npcPed4)
        DeletePed(npcPed5)
        DeletePed(npcPed6)
        DeletePed(npcPed7)
        RenderScriptCams(false, false, 0, true, false)
        DestroyCam(cam)
        SetEntityCoords(playerPed, Config.SpawnIllegalEntry)
        SetEntityHeading(playerPed, Config.SpawnIllegalEntryHeading)
        SetCamActive(cam, false)
        SetCamActiveWithInterp(cam, false, 1000, 1, 1)
        TriggerServerEvent('GMD_Entry:SetEntryBucket')
        PlayerNearIllegalNPC = true
        DoScreenFadeIn(2000)
        PlayerInEntry = false
    end)
    else
        Config.OwnIllegalCutscene()
    end
end)

-- legal cutscene
RegisterNetEvent('GMD_Entry:LegalCutscene')
AddEventHandler('GMD_Entry:LegalCutscene', function(source)
    if Config.UseLegalCutscene then
    local playerPed = PlayerPedId()
    DoScreenFadeOut(1000)
    Wait(1000)
    SetEntityCoords(playerPed, -288.618, -382.646, 169.919, false, false, false, false)
    PlayerInEntry = true
    SetPlayerInvincible(playerPed, true)
    ESX.Game.SpawnVehicle('nimbus', vector3(-288.618, -382.646, 169.919), 162.00, function(airplane)
        SetEntityAsMissionEntity(airplane, true, true)
        SetPedIntoVehicle(playerPed, airplane, 5)
        local cam = CreateCam("DEFAULT_SCRIPTED_CAMERA", true)
        SetCamActive(cam, true)
        RenderScriptCams(true, false, 0, true, false)
        local npcpilot = Config.LegalPedPilot
        RequestModel(npcpilot)
        while not HasModelLoaded(npcpilot) do
            Citizen.Wait(10)
        end
        local npcfillerfemale = Config.LegalPedFiller
        RequestModel(npcfillerfemale)
        while not HasModelLoaded(npcfillerfemale) do
            Citizen.Wait(10)
        end
        local npcfillermale = Config.LegalPedFiller2
        RequestModel(npcfillermale)
        while not HasModelLoaded(npcfillermale) do
            Citizen.Wait(10)
        end
        SetCamCoord(cam, GetEntityCoords(airplane))
        SetCamFov(cam, 50.0)
        AttachCamToEntity(cam, airplane, 0.0, 10.0, 0.8, true)
        PointCamAtCoord(cam, GetEntityCoords(airplane))
        local npcPed = CreatePed(4, npcpilot, -288.618, -382.646, 169.919, 162.0, true, false)
        local npcPed2 = CreatePed(4, npcpilot, -288.618, -382.646, 169.919, 162.0, true, false)
        local npcPedFill = CreatePed(4, npcfillerfemale, -288.618, -382.646, 169.919, 162.0, true, false)
        local npcPedFill2 = CreatePed(4, npcfillermale, -288.618, -382.646, 169.919, 162.0, true, false)
        SetPedIntoVehicle(npcPed, airplane, -1)
        SetPedIntoVehicle(npcPed2, airplane, -2)
        SetEntityAsMissionEntity(npcPed, true, true)
        SetEntityAsMissionEntity(npcPed2, true, true)
        SetPedIntoVehicle(npcPedFill2, airplane, 0)
        SetPedIntoVehicle(npcPedFill, airplane, 1)
        SetPedIntoVehicle(npcPedFill2, airplane, 2)
        SetPedIntoVehicle(npcPedFill2, airplane, 3)
        SetEntityAsMissionEntity(npcPedFill, true, true)
        SetEntityAsMissionEntity(npcPed2, true, true)
        SetModelAsNoLongerNeeded(npcpilot)
        SetDriverAbility(npcPed, 1.0)
        SetDriverAggressiveness(npcPed, 0.0)
        SetDriverAggressiveness(npcPed2, 0.0)
        SetDriverAggressiveness(npcPedFill2, 0.0)
        SetDriverAggressiveness(npcPedFill, 0.0)
        SetEntityHeading(airplane, 226.932)
        TaskVehicleDriveToCoordLongrange(npcPed, airplane, -786.318, -1192.764, 177.599, 10.0, 1, GetEntityModel(airplane), 1074528293, 1.0, true)
        TaskPlaneLand(npcPed, airplane, -1209.126, -1991.744, 110.210, -1654.360, -2762.084, 13.944)
        Wait(5000)
        Config.LegalCutsceneText1()
        Wait(1500)
        DoScreenFadeIn(1500)
        SetCamActive(cam, true)
        RenderScriptCams(true, false, 0, true, false)
        SetCamCoord(cam, GetEntityCoords(playerPed))
        SetCamFov(cam, 50.0)
        AttachCamToEntity(cam, playerPed, 0.0, 2.0, 0.8, true)
        PointCamAtEntity(cam, playerPed, 0.0, 0.0, 0.0, true)
        Config.LegalCutsceneText2()
        Wait(5000)
        SetEntityCoords(airplane, -1266.948, -3013.000, -49.491)
        SetEntityHeading(airplane,  357.711)
        SetEntityCoords(playerPed, -1273.955, -3005.200, -48.490)
        SetEntityHeading(playerPed, 264.924)
        SetEntityCoords(npcPed, -1271.315, -3004.500, -48.490)
        SetEntityHeading(npcPed, 125.413)
        SetDriverAggressiveness(npcPed, 0.0)
        FreezeEntityPosition(airplane, true)
        Wait(3500)
        SetCamCoord(cam, GetEntityCoords(playerPed))
        SetCamFov(cam, 50.0)
        AttachCamToEntity(cam, playerPed, 0.0, -2.0, 0.8, true)
        PointCamAtEntity(cam, playerPed, 0.0, 0.0, 0.0, true)
        Config.LegalCutsceneText3()
        TaskGoStraightToCoord(playerPed, -1240.234, -2993.774, -48.490, 1.0, -1, 1.0, 0.0)
        TaskGoStraightToCoord(npcPed, -1240.234, -2993.774, -48.490, 1.0, -1, 1.0, 0.0)
        Wait(3000)
        DoScreenFadeOut(2000)
        Wait(2500)
        SetEntityCoords(playerPed, Config.SpawnLegalEntry)
        SetEntityHeading(playerPed, Config.SpawnLegalEntryHeading)
        ClearPedTasks(playerPed)
        DeletePed(npcPed)
        DeletePed(npcPed2)
        DeletePed(npcPedFill)
        DeletePed(npcPedFill2)
        SetEntityAsMissionEntity(airplane, false, false)
        DeleteVehicle(airplane)
        RenderScriptCams(false, false, 0, true, false)
        DestroyCam(cam, true)
        Wait(2500)
        PlayerInEntry = false
        PlayerNearLegalNPC = true
        DoScreenFadeIn(1500)
        Wait(2000)
        TriggerServerEvent('GMD_Entry:SetEntryBucket')
    end)
    else
        Config.OwnLegalCutscene()
    end
end)

function EnableNUI(state)
    SetNuiFocus(state, state)
    EnabledNUI = state
    SendNUIMessage({ type = "enableui", enable = state })
end

-- function PlayerEntrySceen(playerid)
--     DoScreenFadeOut(1000)
--     SetEntityCoords(playerid, Config.SpawnLegalEntry)
--     SetEntityHeading(playerid, Config.SpawnLegalEntryHeading)
--     Wait(500)
--     DoScreenFadeIn(1000)
-- end

-- function PlayCamChange()
--     FreezeEntityPosition(GetPlayerPed(), true)
--     cam = CreateCamWithParams("DEFAULT_SCRIPTED_CAMERA", Config.EnterCoords[1], Config.EnterCoords[2],
--         Config.EnterCoords[3] + 250.0, 300.00, 0.00, 0.00, 70.00, false, 0)
--     PointCamAtCoord(cam, Config.EnterCoords[1], Config.EnterCoords[2], Config.EnterCoords[3] + 2.0)
--     SetCamActive(cam, true)
--     RenderScriptCams(true, true, Config.CamWait, true, true)
--     Wait(Config.CamWait)
-- end